//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igo_Font
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp
    {
        public int TempID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> SeatID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
